config/urls.py
import notifications.urls

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from webpush.views import save_info

from .views import (
    offline_view,
    send_notification,
    service_worker,
    service_worker_map,
    mark_all_read,
    mark_as_read,
    support,
)
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path(
        "products/vendify/", TemplateView.as_view(template_name="pages/vendify.html"), name="vendify"
    ),
    path(
        "products/trustpay/", TemplateView.as_view(template_name="pages/trustpay.html"), name="trustpay"
    ),
    path("support/", support, name="support"),
    path("offline/", offline_view, name="offline"),
    path("all-read/", mark_all_read, name="all_read"),
    path("read/<id>/", mark_as_read, name="read"),

    # PWA Urls
    path("sw.js", service_worker, name="service_worker"),
    path("sw.js.map", service_worker_map, name="service_worker_map"),

    # Django Admin, use {% url 'admin:index' %}
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path(
        "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    ),  # Django JET dashboard URLS
    # path("admin/", include("admin_honeypot.urls", "admin_honeypot")),
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),

    # User management
    path("users/", include("trustcrow.users.urls", namespace="users")),
    path("users/create/new-contract/", TemplateView.as_view(template_name="users/new_contract.html"), name="new_contract"),
    path("escrow/", include("trustcrow.escrow.urls", namespace="escrow")),
    path("accounts/", include("allauth.urls")),

    # Your stuff: custom urls includes go here
    # push notification links
    path("send-notification/", send_notification, name="send_notification"),
    path("webpush/save_information/", view=save_info, name="save_webpush_info"),
    path("webpush/", include("webpush.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# MISC URLS
urlpatterns += [
    path("tinymce/", include("tinymce.urls")),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml/", sitemap, kwargs={"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

trustcrow/escrow/urls.py
from django.urls import path

from trustcrow.escrow.views import (
    create_contract,
    vendor_approve,

    create_milestones,
    add_milestones_form,
    milestone_approve,
    detail_milestone,

    approve_product,
    detail_product,
    create_product,
    add_product_form,

    contract_detail,
    contract_detail2,
    list_contracts,
    search_contracts,
    verify_transaction,
    transaction_data,
    list_transactions,
    retry_payment,
    payment_sent,
    # complete_payment,


    # create_contract_service,
    # create_contract_service_milestone,
    # complete_milestone,

    list_customers,
)

app_name = "escrow"
urlpatterns = [
    # contract links
    path("contract/create/", view=create_contract, name="create_contract"),
    path("contract/vendor/approve/<slug>/", view=vendor_approve, name="vendor_approve"),
    path("contract/milestone/approve/<pk>/", view=milestone_approve, name="milestone_approve"),
    path("contract/milestones/<slug>/create/", view=create_milestones, name="create_milestones"),
    path("contract/milestones/<slug>/add-form/", view=add_milestones_form, name="add_milestones_form"),
    path("contract/milestones/<pk>/", view=detail_milestone, name="detail_milestone"),
    path("contract/product/approve/<pk>/", view=approve_product, name="approve_product"),
    path("contract/product/<slug>/create/", view=create_product, name="create_product"),
    path("contract/product/<slug>/add-form/", view=add_product_form, name="add_product_form"),
    path("contract/product/<pk>/", view=detail_product, name="detail_product"),
    path("contract/list/", view=list_contracts, name="list_contracts"),
    path("contract/list/search/", view=search_contracts, name="search_contracts"),
    path("contract/detail/<slug>/", view=contract_detail, name="contract_detail"),
    path("contract/detail/<slug>/<username>/", view=contract_detail2, name="contract_detail2"),
    path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/", view=payment_sent, name="payment_sent"),
    # path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/completed/", view=complete_payment, name="complete_payment"),

    # customers
    path("customers/list/", view=list_customers, name="list_customers"),

    # transactions
    path("transaction/data/", view=transaction_data, name="transaction_data"),
    path("transaction/list/", view=list_transactions, name="list_transactions"),
    path("transaction/verify/<str:ref>/<str:status>/", view=verify_transaction, name="verify_transaction"),
    path("transaction/retry/<str:ref_link>/", view=retry_payment, name="retry_payment"),

    # path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/users/urls.py
from django.urls import path

from trustcrow.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,

    all_users,
    list_products,
    product_detail_view,
    search_products,
    create_product,
    
    add_bank
)

app_name = "users"
urlpatterns = [
    path("", view=all_users, name="all"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),

    path("banks/add/", view=add_bank, name="add_bank"),

    path("workshop/products/search/", view=search_products, name="search_products"),
    path("workshop/products/", view=list_products, name="list_products"),
    path("workshop/products/create/", view=create_product, name="create_product"),
    path("workshop/products/<int:pk>/edit/", view=product_detail_view, name="product_detail"),

    path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/escrow/forms.py
from datetime import datetime

from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from allauth.account.forms import SignupForm, LoginForm
from countries_plus.models import Country
from trustcrow.users.models import Profile

from .models import (
    Contract,
    Transactions,
    Milestones,
    Dispute,
    DisputeMessages,
)

from trustcrow.utils.logger import LOGGER

User = get_user_model()


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = [
            "contract_title",
            'creator',
            'contract_amount',
            "contract_type",
            "vendor",
            "vendor_phone",
            "vendor_email",
            "vendor_address",
            "buyer",
            "buyer_phone",
            "buyer_email",
            "buyer_address",
            "terms_agreement",
            "terms_for_termination",
        ]


    def clean_vendor(self):
        data = self.cleaned_data['vendor']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_contract_title(self):
        data = self.cleaned_data['contract_title']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_vendor_phone(self):
    #     data = self.cleaned_data['vendor_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(company_phone_I=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a vendor!"))
    #     return data


    def clean_vendor_email(self):
        data = self.cleaned_data['vendor_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        # if User.objects.filter(email=data).exists() and "@" in data:
        #     user = User.objects.get(email=data)
        #     default = "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541"
        #     raise ValidationError(mark_safe(
        #         f"This email belongs to an existing Business / Marchant! <button class='btn-black btn-rounded hover:font-bold duration-300' type='button' data-tooltip-target='tooltip-animation'  data-tooltip-trigger='click'>{user.profile.company_name.title() if user.profile.company_name else user.username}</button> <div id='tooltip-animation' role='tooltip' class='inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-black rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700 space-y-2'><div class='flex items-center'><img class='block h-10 w-10 rounded-full object-fit overflow-hidden hover:object-cover duration-300 flex-none' alt='{user.profile.company_name.title() if user.profile.company_name else user.username}' src='{user.image.thumbnail.url if user.image else default}'><div class='block space-y-2'><a href='{user.get_absolute_url()}' target='_blank' class='block font-semibold hover:font-bold duration-300 text-base'>{user.profile.company_name.title() if user.profile.company_name else user.username}</a><p class='text-s font-medium'>{user.email}</p></div></div><div class='tooltip-arrow' data-popper-arrow></div></div>"))
        return data


    def clean_vendor_address(self):
        data = self.cleaned_data['vendor_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_buyer(self):
        data = self.cleaned_data['buyer']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_buyer_phone(self):
    #     data = self.cleaned_data['buyer_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(phone=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a buyer!"))
    #     return data


    def clean_buyer_email(self):
        data = self.cleaned_data['buyer_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


    def clean_buyer_address(self):
        data = self.cleaned_data['buyer_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestones
        fields = [
            "detail",
            "deadline",
            "price",
        ]

MilestonesFormset = forms.inlineformset_factory(
    Contract,
    Milestones,
    form=MilestoneForm,
    extra=1,
    can_delete=False,
    # can_delete_extra=True,
    min_num=0,
    validate_min=True
)





class DisputeForm(forms.ModelForm):
    class Meta:
        model = Dispute
        fields = [
            "dispute_detail",
            "dispute_resolve",
        ]

class DisputeMessageForm(forms.ModelForm):
    class Meta:
        model = DisputeMessages
        fields = [
            "message"
        ]

trustcrow/orders/forms.py
from django import forms

from .models import Order, OrderItems

# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['vendor', 'buyer', 'contract']


# class OrderItemForm(forms.ModelForm):
#     class Meta:
#         model = OrderItems
#         fieds = [
#             "id",
#             "order",
#             "product",
#             "quantity",
#             "price",
#         ]

trustcrow/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

trustcrow/workshop/forms.py
from django import forms

from .models import Products, ProductImage

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['title', 'detail', 'price', 'p_type']

trustcrow/currency/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import BankSerializer

from trustcrow.currency.models import Banks


class BankViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = BankSerializer
    queryset = Banks.objects.all()
    lookup_field = "id"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.kwargs['id'], int)
        return self.queryset.filter(id=self.kwargs['id'])

trustcrow/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

trustcrow/templates/shop/create_product.html
{% extends "dashboard.html" %}
{% load humanize static %}

{% block title %}
{{ block.super }} Create Product
{% endblock title %}

{% block content %}
<section class="space-y-10 w-full p-4 md:px-10 md:py-8 min-h-[calc(100vh_-_14rem)]">
    <form action="{% url 'users:create_product' %}" method="post" enctype="multipart/form-data" class="rounded-xl bg-white text-gray-700 p-4 space-y-4">
        {% csrf_token %}
        <div class="md:flex md:items-start md:space-x-4 space-y-4 md:space-y-0">
            <div class="flex md:block md:space-y-3 md:space-x-0 space-x-3">
                <!-- <div class="flex-none">
                    <div class="w-32 h-32 mb-1 border rounded-lg overflow-hidden relative bg-gray-100">
                        <img id="imageI" class="object-cover w-full h-32" src="https://placehold.co/300x300/e2e8f0/e2e8f0" />

                        <div class="absolute top-0 left-0 right-0 bottom-0 w-full block cursor-pointer flex items-center justify-center" onClick="document.getElementById('fileInputI').click()">
                        <button type="button"
                            style="background-color: rgba(255, 255, 255, 0.65)"
                            class="hover:bg-gray-100 text-gray-700 font-semibold py-2 px-4 text-sm border border-gray-300 rounded-lg shadow-sm"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-camera" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                                <path d="M5 7h1a2 2 0 0 0 2 -2a1 1 0 0 1 1 -1h6a1 1 0 0 1 1 1a2 2 0 0 0 2 2h1a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2" />
                                <circle cx="12" cy="13" r="3" />
                            </svg>
                        </button>
                        </div>
                    </div>
                    <input name="img1" id="fileInputI" accept="image/*" class="hidden" type="file" onChange="
                        let fileI = this.files[0];
                        var reader = new FileReader();

                        reader.onload = function (e) {
                        document.getElementById('imageI').src = e.target.result;
                        document.getElementById('image2').src = e.target.result;
                        };

                        reader.readAsDataURL(fileI);
                    ">
                </div>
                <div class="flex-none">
                    <div class="w-32 h-32 mb-1 border rounded-lg overflow-hidden relative bg-gray-100">
                        <img id="imageII" class="object-cover w-full h-32" src="https://placehold.co/300x300/e2e8f0/e2e8f0" />

                        <div class="absolute top-0 left-0 right-0 bottom-0 w-full block cursor-pointer flex items-center justify-center" onClick="document.getElementById('fileInputII').click()">
                        <button type="button"
                            style="background-color: rgba(255, 255, 255, 0.65)"
                            class="hover:bg-gray-100 text-gray-700 font-semibold py-2 px-4 text-sm border border-gray-300 rounded-lg shadow-sm"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-camera" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                            <path d="M5 7h1a2 2 0 0 0 2 -2a1 1 0 0 1 1 -1h6a1 1 0 0 1 1 1a2 2 0 0 0 2 2h1a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2" />
                            <circle cx="12" cy="13" r="3" />
                            </svg>
                        </button>
                        </div>
                    </div>
                    <input name="img2" id="fileInputII" accept="image/*" class="hidden" type="file" onChange="
                        let fileII = this.files[0];
                        var reader = new FileReader();

                        reader.onload = function (e) {
                        document.getElementById('imageII').src = e.target.result;
                        document.getElementById('image2').src = e.target.result;
                        };

                        reader.readAsDataURL(fileII);
                    ">
                </div> -->
            </div>

            <div class="space-y-3 w-full md:w-[calc(100%_-_128px)]">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div class="relative">
                        <input type="text" name="title" id="id_title" required class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-warning/60 focus:outline-none focus:ring-0 focus:border-warning peer">
                        <label for="id_title" class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Product Title</label>
                    </div>
                    <div class="relative">
                        <input type="number" step="0.01" min="100.00" max="1000000.00" name="price" id="id_price" required class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-warning/60 focus:outline-none focus:ring-0 focus:border-warning peer">
                        <label for="id_price" class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Product Unit Price</label>
                    </div>
                </div>

                <div class="relative">
                    <textarea name="detail" id="id_detail" cols="100" rows="5" class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-warning/60 focus:outline-none focus:ring-0 focus:border-warning peer w-full"></textarea>
                    <label for="id_detail" class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Product Detail</label>
                </div>
            </div>
        </div>
        <button type="submit" class="bg-warning px-6 py-3 rounded-xl text-center md:w-1/3">Submit</button>
    </form>
</section>
{% endblock content %}

trustcrow/templates/shop/product_list.html
{% extends "dashboard.html" %}

{% block title %}
{{ block.super }} {{request.user.username|title}} Products
{% endblock title %}

{% block content %}
<div x-data="{filter:0}" class="space-y-10 w-full p-4 md:px-10 md:py-8 min-h-[calc(100vh_-_14rem)]">
    <div class="md:w-full md:max-w-2xl w-full ">
        <div class="flex">
            <label for="search-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Your
                Email</label>
            <button id="dropdown-search-button" data-dropdown-toggle="dropdown-search"
                class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-l-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600"
                type="button">Filters <svg aria-hidden="true" class="w-4 h-4 ml-1" fill="currentColor"
                    viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                </svg></button>
            <div id="dropdown-search"
                class="z-10 hidden bg-white divide-y divide-gray-100 rounded shadow w-44 dark:bg-gray-700"
                data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="top"
                style="position: absolute; inset: auto auto 0px 0px; margin: 0px; transform: translate3d(897px, 5637px, 0px);">
                <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-search-button">
                    <li>
                        <button @click="filter = 0" type="button"
                            class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">All</button>
                    </li>
                    <li>
                        <button @click="filter = 2" type="button"
                            class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Services</button>
                    </li>
                    <li>
                        <button @click="filter = 1" type="button"
                            class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Products</button>
                    </li>
                </ul>
            </div>
            <form method="GET" action="" class="relative w-full">
                <input name="q" hx-get="{% url 'users:search_products' %}" hx-swap="innerHTML" hx-target="#escrow"
                    hx-trigger="keyup changed delay:300ms" type="search" id="search-dropdown"
                    class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-r-lg border-l-gray-50 border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-l-gray-700  dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500"
                    placeholder="Search Vendor Names, Buyer Name, Contract ID..." required name="search">
                <button type="submit"
                    class="absolute top-0 right-0 p-2.5 text-sm font-medium text-white bg-warning rounded-r-lg border border-warning hover:bg-warning focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-warning/70 dark:hover:bg-warning/800 dark:focus:ring-warning">
                    <svg aria-hidden="true" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                    <span class="sr-only">Search</span>
                </button>
            </form>
        </div>
    </div>

    <section id="escrow" class="w-full divide-y-3 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        {% include "snippets/htmx/user_product_list.html" %}
    </section>
</div>
{% endblock content %}