config/urls.py
import notifications.urls

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from webpush.views import save_info

from .views import (
    offline_view,
    send_notification,
    service_worker,
    service_worker_map,
    mark_all_read,
    mark_as_read,
    support,
)
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path(
        "products/vendify/", TemplateView.as_view(template_name="pages/vendify.html"), name="vendify"
    ),
    path(
        "products/trustpay/", TemplateView.as_view(template_name="pages/trustpay.html"), name="trustpay"
    ),
    path("support/", support, name="support"),
    path("offline/", offline_view, name="offline"),
    path("all-read/", mark_all_read, name="all_read"),
    path("read/<id>/", mark_as_read, name="read"),

    # PWA Urls
    path("sw.js", service_worker, name="service_worker"),
    path("sw.js.map", service_worker_map, name="service_worker_map"),

    # Django Admin, use {% url 'admin:index' %}
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path(
        "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    ),  # Django JET dashboard URLS
    # path("admin/", include("admin_honeypot.urls", "admin_honeypot")),
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),

    # User management
    path("users/", include("trustcrow.users.urls", namespace="users")),
    path("users/create/new-contract/", TemplateView.as_view(template_name="users/new_contract.html"), name="new_contract"),
    path("escrow/", include("trustcrow.escrow.urls", namespace="escrow")),
    path("accounts/", include("allauth.urls")),

    # Your stuff: custom urls includes go here
    # push notification links
    path("send-notification/", send_notification, name="send_notification"),
    path("webpush/save_information/", view=save_info, name="save_webpush_info"),
    path("webpush/", include("webpush.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# MISC URLS
urlpatterns += [
    path("tinymce/", include("tinymce.urls")),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml/", sitemap, kwargs={"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

trustcrow/escrow/urls.py
from django.urls import path

from trustcrow.escrow.views import (
    create_contract,
    vendor_approve,

    create_milestones,
    add_milestones_form,
    milestone_approve,
    detail_milestone,

    approve_product,
    detail_product,
    create_product,
    add_product_form,

    contract_detail,
    contract_detail2,
    list_contracts,
    search_contracts,
    verify_transaction,
    transaction_data,
    list_transactions,
    retry_payment,
    payment_sent,
    # complete_payment,


    # create_contract_service,
    # create_contract_service_milestone,
    # complete_milestone,

    list_customers,
)

app_name = "escrow"
urlpatterns = [
    # contract links
    path("contract/create/", view=create_contract, name="create_contract"),
    path("contract/vendor/approve/<slug>/", view=vendor_approve, name="vendor_approve"),
    path("contract/milestone/approve/<pk>/", view=milestone_approve, name="milestone_approve"),
    path("contract/milestones/<slug>/create/", view=create_milestones, name="create_milestones"),
    path("contract/milestones/<slug>/add-form/", view=add_milestones_form, name="add_milestones_form"),
    path("contract/milestones/<pk>/", view=detail_milestone, name="detail_milestone"),
    path("contract/product/approve/<pk>/", view=approve_product, name="approve_product"),
    path("contract/product/<slug>/create/", view=create_product, name="create_product"),
    path("contract/product/<slug>/add-form/", view=add_product_form, name="add_product_form"),
    path("contract/product/<pk>/", view=detail_product, name="detail_product"),
    path("contract/list/", view=list_contracts, name="list_contracts"),
    path("contract/list/search/", view=search_contracts, name="search_contracts"),
    path("contract/detail/<slug>/", view=contract_detail, name="contract_detail"),
    path("contract/detail/<slug>/<username>/", view=contract_detail2, name="contract_detail2"),
    path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/", view=payment_sent, name="payment_sent"),
    # path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/completed/", view=complete_payment, name="complete_payment"),

    # customers
    path("customers/list/", view=list_customers, name="list_customers"),

    # transactions
    path("transaction/data/", view=transaction_data, name="transaction_data"),
    path("transaction/list/", view=list_transactions, name="list_transactions"),
    path("transaction/verify/<str:ref>/<str:status>/", view=verify_transaction, name="verify_transaction"),
    path("transaction/retry/<str:ref_link>/", view=retry_payment, name="retry_payment"),

    # path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/users/urls.py
from django.urls import path

from trustcrow.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,

    all_users,
    list_products,
    product_detail_view,
    search_products,
    create_product,
    
    add_bank
)

app_name = "users"
urlpatterns = [
    path("", view=all_users, name="all"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),

    path("banks/add/", view=add_bank, name="add_bank"),

    path("workshop/products/search/", view=search_products, name="search_products"),
    path("workshop/products/", view=list_products, name="list_products"),
    path("workshop/products/create/", view=create_product, name="create_product"),
    path("workshop/products/<int:pk>/edit/", view=product_detail_view, name="product_detail"),

    path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/escrow/forms.py
from datetime import datetime

from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from allauth.account.forms import SignupForm, LoginForm
from countries_plus.models import Country
from trustcrow.users.models import Profile

from .models import (
    Contract,
    Transactions,
    Milestones,
    Dispute,
    DisputeMessages,
)

from trustcrow.utils.logger import LOGGER

User = get_user_model()


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = [
            "contract_title",
            'creator',
            'contract_amount',
            "contract_type",
            "vendor",
            "vendor_phone",
            "vendor_email",
            "vendor_address",
            "buyer",
            "buyer_phone",
            "buyer_email",
            "buyer_address",
            "terms_agreement",
            "terms_for_termination",
        ]


    def clean_vendor(self):
        data = self.cleaned_data['vendor']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_contract_title(self):
        data = self.cleaned_data['contract_title']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_vendor_phone(self):
    #     data = self.cleaned_data['vendor_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(company_phone_I=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a vendor!"))
    #     return data


    def clean_vendor_email(self):
        data = self.cleaned_data['vendor_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        # if User.objects.filter(email=data).exists() and "@" in data:
        #     user = User.objects.get(email=data)
        #     default = "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541"
        #     raise ValidationError(mark_safe(
        #         f"This email belongs to an existing Business / Marchant! <button class='btn-black btn-rounded hover:font-bold duration-300' type='button' data-tooltip-target='tooltip-animation'  data-tooltip-trigger='click'>{user.profile.company_name.title() if user.profile.company_name else user.username}</button> <div id='tooltip-animation' role='tooltip' class='inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-black rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700 space-y-2'><div class='flex items-center'><img class='block h-10 w-10 rounded-full object-fit overflow-hidden hover:object-cover duration-300 flex-none' alt='{user.profile.company_name.title() if user.profile.company_name else user.username}' src='{user.image.thumbnail.url if user.image else default}'><div class='block space-y-2'><a href='{user.get_absolute_url()}' target='_blank' class='block font-semibold hover:font-bold duration-300 text-base'>{user.profile.company_name.title() if user.profile.company_name else user.username}</a><p class='text-s font-medium'>{user.email}</p></div></div><div class='tooltip-arrow' data-popper-arrow></div></div>"))
        return data


    def clean_vendor_address(self):
        data = self.cleaned_data['vendor_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_buyer(self):
        data = self.cleaned_data['buyer']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_buyer_phone(self):
    #     data = self.cleaned_data['buyer_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(phone=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a buyer!"))
    #     return data


    def clean_buyer_email(self):
        data = self.cleaned_data['buyer_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


    def clean_buyer_address(self):
        data = self.cleaned_data['buyer_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestones
        fields = [
            "detail",
            "deadline",
            "price",
        ]

MilestonesFormset = forms.inlineformset_factory(
    Contract,
    Milestones,
    form=MilestoneForm,
    extra=1,
    can_delete=False,
    # can_delete_extra=True,
    min_num=0,
    validate_min=True
)





class DisputeForm(forms.ModelForm):
    class Meta:
        model = Dispute
        fields = [
            "dispute_detail",
            "dispute_resolve",
        ]

class DisputeMessageForm(forms.ModelForm):
    class Meta:
        model = DisputeMessages
        fields = [
            "message"
        ]

trustcrow/orders/forms.py
from django import forms

from .models import Order, OrderItems

# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['vendor', 'buyer', 'contract']


# class OrderItemForm(forms.ModelForm):
#     class Meta:
#         model = OrderItems
#         fieds = [
#             "id",
#             "order",
#             "product",
#             "quantity",
#             "price",
#         ]

trustcrow/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

trustcrow/workshop/forms.py
from django import forms

from .models import Products, ProductImage

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['title', 'detail', 'price', 'p_type']

trustcrow/currency/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import BankSerializer

from trustcrow.currency.models import Banks


class BankViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = BankSerializer
    queryset = Banks.objects.all()
    lookup_field = "id"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.kwargs['id'], int)
        return self.queryset.filter(id=self.kwargs['id'])

trustcrow/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

trustcrow/templates/snippets/htmx/escrow_customer_list.html
{% load humanize %}

{% for c in objects %}
{% if forloop.last and page_obj.has_next %}
<div hx-get="{% url 'escrow:list_contracts' %}?page={{ page_obj.number|add:1 }}" hx-swap="afterend" hx-trigger="revealed" hx-target="this" class="cursor-pointer group duration-300 flex items-center space-x-4 bg-gray-100 p-3 rounded-xl hover:shadow-md justify-between">
{% else %}
<div class="cursor-pointer group duration-300 flex items-center space-x-4 bg-gray-100 p-3 rounded-xl hover:shadow-md justify-between">
{% endif %}
  <div class="flex items-center space-x-4">
    <img src="{% if c.image %}{{c.image.url}}{% else %}https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png{% endif %}" alt="{{c.user.username}}" class="h-12 w-12 object-cover rounded-full block">
    <div class="space-y-0 flex flex-col">
      <h4 class="font-bold text-base">UN: {% if c.name %}{{c.name}}{% else %}{{c.username}}{% endif %}</h4>
      <p class="block text-s font-bold text-primary">EM: {% if c.email %}{{c.email}}{% else %}None{% endif %}</p>
      <p class="block text-s font-bold text-gray-500">PN: {% if c.profile.phone %}{{c.profile.phone}}{% else %}None{% endif %}</p>
    </div>
  </div>

  <a class="w-8 h-8 hidden flex-none duration-300 group-hover:block" href="mailto://{{c.email}}">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
      <path d="M1.5 8.67v8.58a3 3 0 003 3h15a3 3 0 003-3V8.67l-8.928 5.493a3 3 0 01-3.144 0L1.5 8.67z" />
      <path d="M22.5 6.908V6.75a3 3 0 00-3-3h-15a3 3 0 00-3 3v.158l9.714 5.978a1.5 1.5 0 001.572 0L22.5 6.908z" />
    </svg>
  </a>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 block flex-none duration-300 group-hover:hidden">
    <path fill-rule="evenodd" d="M17.834 6.166a8.25 8.25 0 100 11.668.75.75 0 011.06 1.06c-3.807 3.808-9.98 3.808-13.788 0-3.808-3.807-3.808-9.98 0-13.788 3.807-3.808 9.98-3.808 13.788 0A9.722 9.722 0 0121.75 12c0 .975-.296 1.887-.809 2.571-.514.685-1.28 1.179-2.191 1.179-.904 0-1.666-.487-2.18-1.164a5.25 5.25 0 11-.82-6.26V8.25a.75.75 0 011.5 0V12c0 .682.208 1.27.509 1.671.3.401.659.579.991.579.332 0 .69-.178.991-.579.3-.4.509-.99.509-1.671a8.222 8.222 0 00-2.416-5.834zM15.75 12a3.75 3.75 0 10-7.5 0 3.75 3.75 0 007.5 0z" clip-rule="evenodd" />
  </svg>
</div>
{% empty %}
<div class="col-span-4 rounded-xl shadow-xl bg-white text-gray-800 py-8 text-center space-y-3">
  <p class="text-base text-gray-400 block">You do not have a customer</p>
</div>
{% endfor %}

trustcrow/templates/snippets/htmx/escrow_transaction_list.html
{% load humanize %}

{% for tx in objects %}
{% if forloop.last and page_obj.has_next %}
<div x-data="ContractDetailForm" hx-get="{% url 'escrow:list_transactions' %}?page={{ page_obj.number|add:1 }}" hx-swap="afterend" hx-trigger="revealed" hx-target="this" x-show.transition.in="filter == {% if tx.contract.payment_withdrawn and tx.contract.payment_sent %}1{% elif not tx.contract.payment_withdrawn and not tx.contract.payment_sent %}2{% endif %} || filter == 0" class="hover:shadow-md bg-gray-100 p-3 rounded-xl duration-500 space-y-3">
{% else %}
<div x-data="ContractDetailForm" x-show.transition.in="filter == {% if tx.contract.payment_withdrawn and tx.contract.payment_sent %}1{% elif not tx.contract.payment_withdrawn and not tx.contract.payment_sent %}2{% endif %} || filter == 0"  class="hover:shadow-md bg-gray-100 p-3 rounded-xl duration-500 space-y-3">
{% endif %}
  <div class="flex items-center justify-between">
    <div class="flex items-center space-x-4">
      <div class="p-4 bg-gray-200 text-gray-700 rounded-full">
        {% if tx.contract.vendor_email == request.user.email %}
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-success/50">
          <path d="M12 7.5a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z" />
          <path fill-rule="evenodd" d="M1.5 4.875C1.5 3.839 2.34 3 3.375 3h17.25c1.035 0 1.875.84 1.875 1.875v9.75c0 1.036-.84 1.875-1.875 1.875H3.375A1.875 1.875 0 011.5 14.625v-9.75zM8.25 9.75a3.75 3.75 0 117.5 0 3.75 3.75 0 01-7.5 0zM18.75 9a.75.75 0 00-.75.75v.008c0 .414.336.75.75.75h.008a.75.75 0 00.75-.75V9.75a.75.75 0 00-.75-.75h-.008zM4.5 9.75A.75.75 0 015.25 9h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H5.25a.75.75 0 01-.75-.75V9.75z" clip-rule="evenodd" />
          <path d="M2.25 18a.75.75 0 000 1.5c5.4 0 10.63.722 15.6 2.075 1.19.324 2.4-.558 2.4-1.82V18.75a.75.75 0 00-.75-.75H2.25z" />
        </svg>
        {% else %}
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-danger/50">
          <path d="M4.5 3.75a3 3 0 00-3 3v.75h21v-.75a3 3 0 00-3-3h-15z" />
          <path fill-rule="evenodd" d="M22.5 9.75h-21v7.5a3 3 0 003 3h15a3 3 0 003-3v-7.5zm-18 3.75a.75.75 0 01.75-.75h6a.75.75 0 010 1.5h-6a.75.75 0 01-.75-.75zm.75 2.25a.75.75 0 000 1.5h3a.75.75 0 000-1.5h-3z" clip-rule="evenodd" />
        </svg>
        {% endif %}
      </div>
      <div>
        {% if tx.vendor %}
        <strong class="text-base font-bold block">From {% if tx.buyer.name %}{{tx.buyer.name|title}}{% else %}{{tx.buyer.username|title}}{% endif %}</strong>
        {% else %}
        <strong class="text-base font-bold block">To {% if tx.vendor.name %}{{tx.vendor.name|title}}{% else %}{{tx.vendor.username|title}}{% endif %}</strong>
        {% endif %}
        <p class="text-normal text-gray-300 text-s">{{tx.modified|date:"M d, Y"}}</p>
      </div>
    </div>
    <div class="text-right">
      {% if tx.contract.payment_sent %}
      <strong class="text-base font-bold block text-success">+ {{tx.total_cost}}</strong>
      <p class="text-normal text-gray-300 text-s">Amount Recieved</p>
      {% else %}
      <strong class="text-base font-bold block text-danger">- {{tx.total_cost}}</strong>
      <p class="text-normal text-gray-300 text-s">Amount Spent</p>
      {% endif %}
    </div>
  </div>
  {% if not request.user.get_user_banks and not tx.contract.payment_sent and request.user.email == tx.contract.vendor_email %}
  <a href="{% url 'users:update' %}" class="bg-warning btn-rounded hover:shadow-xl duration 300 w-full py-2 text-center text-gray-700 font-bold">
    <span class="block">REQUEST PAYMENT</span>
  </a>
  {% elif not tx.contract.payment_sent and request.user.email == tx.contract.vendor_email %}
  <button @click="vendor_payout( '{{request.user.username}}', '{{tx.contract.withdraw_amount}}', '{{tx.contract.slug}}', '{{request.user.get_user_banks.acc_no}}', '{{request.user.get_user_banks.bank.code}}', '{{request.user.name}}', '{{tx.ref_link}}' )" class="bg-warning btn-rounded hover:shadow-xl duration 300 w-full py-2 text-center text-gray-700 font-bold">
    <span class="block">REQUEST PAYMENT</span>
  </button>
  {% else %}
  <button class="bg-success text-white btn-rounded hover:shadow-xl duration 300 w-full py-2 text-center font-bold">
    <span class="block">PAYMENT TRANSFERRED</span>
  </button>
  {% endif %}
</div>

{% empty %}
<div class="col-span-4 rounded-xl shadow-xl bg-white text-gray-800 py-8 text-center space-y-3">
  <p class="text-base text-gray-400 block">No Transaction History Present yet</p>
</div>
{% endfor %}