config/urls.py
import notifications.urls

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from webpush.views import save_info

from .views import (
    offline_view,
    send_notification,
    service_worker,
    service_worker_map,
    mark_all_read,
    mark_as_read,
    support,
)
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path(
        "products/vendify/", TemplateView.as_view(template_name="pages/vendify.html"), name="vendify"
    ),
    path(
        "products/trustpay/", TemplateView.as_view(template_name="pages/trustpay.html"), name="trustpay"
    ),
    path("support/", support, name="support"),
    path("offline/", offline_view, name="offline"),
    path("all-read/", mark_all_read, name="all_read"),
    path("read/<id>/", mark_as_read, name="read"),

    # PWA Urls
    path("sw.js", service_worker, name="service_worker"),
    path("sw.js.map", service_worker_map, name="service_worker_map"),

    # Django Admin, use {% url 'admin:index' %}
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path(
        "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    ),  # Django JET dashboard URLS
    # path("admin/", include("admin_honeypot.urls", "admin_honeypot")),
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),

    # User management
    path("users/", include("trustcrow.users.urls", namespace="users")),
    path("users/create/new-contract/", TemplateView.as_view(template_name="users/new_contract.html"), name="new_contract"),
    path("escrow/", include("trustcrow.escrow.urls", namespace="escrow")),
    path("accounts/", include("allauth.urls")),

    # Your stuff: custom urls includes go here
    # push notification links
    path("send-notification/", send_notification, name="send_notification"),
    path("webpush/save_information/", view=save_info, name="save_webpush_info"),
    path("webpush/", include("webpush.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# MISC URLS
urlpatterns += [
    path("tinymce/", include("tinymce.urls")),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml/", sitemap, kwargs={"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

trustcrow/escrow/urls.py
from django.urls import path

from trustcrow.escrow.views import (
    create_contract,
    vendor_approve,

    create_milestones,
    add_milestones_form,
    milestone_approve,
    detail_milestone,

    approve_product,
    detail_product,
    create_product,
    add_product_form,

    contract_detail,
    contract_detail2,
    list_contracts,
    search_contracts,
    verify_transaction,
    transaction_data,
    list_transactions,
    retry_payment,
    payment_sent,
    # complete_payment,


    # create_contract_service,
    # create_contract_service_milestone,
    # complete_milestone,

    list_customers,
)

app_name = "escrow"
urlpatterns = [
    # contract links
    path("contract/create/", view=create_contract, name="create_contract"),
    path("contract/vendor/approve/<slug>/", view=vendor_approve, name="vendor_approve"),
    path("contract/milestone/approve/<pk>/", view=milestone_approve, name="milestone_approve"),
    path("contract/milestones/<slug>/create/", view=create_milestones, name="create_milestones"),
    path("contract/milestones/<slug>/add-form/", view=add_milestones_form, name="add_milestones_form"),
    path("contract/milestones/<pk>/", view=detail_milestone, name="detail_milestone"),
    path("contract/product/approve/<pk>/", view=approve_product, name="approve_product"),
    path("contract/product/<slug>/create/", view=create_product, name="create_product"),
    path("contract/product/<slug>/add-form/", view=add_product_form, name="add_product_form"),
    path("contract/product/<pk>/", view=detail_product, name="detail_product"),
    path("contract/list/", view=list_contracts, name="list_contracts"),
    path("contract/list/search/", view=search_contracts, name="search_contracts"),
    path("contract/detail/<slug>/", view=contract_detail, name="contract_detail"),
    path("contract/detail/<slug>/<username>/", view=contract_detail2, name="contract_detail2"),
    path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/", view=payment_sent, name="payment_sent"),
    # path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/completed/", view=complete_payment, name="complete_payment"),

    # customers
    path("customers/list/", view=list_customers, name="list_customers"),

    # transactions
    path("transaction/data/", view=transaction_data, name="transaction_data"),
    path("transaction/list/", view=list_transactions, name="list_transactions"),
    path("transaction/verify/<str:ref>/<str:status>/", view=verify_transaction, name="verify_transaction"),
    path("transaction/retry/<str:ref_link>/", view=retry_payment, name="retry_payment"),

    # path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/users/urls.py
from django.urls import path

from trustcrow.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,

    all_users,
    list_products,
    product_detail_view,
    search_products,
    create_product,
    
    add_bank
)

app_name = "users"
urlpatterns = [
    path("", view=all_users, name="all"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),

    path("banks/add/", view=add_bank, name="add_bank"),

    path("workshop/products/search/", view=search_products, name="search_products"),
    path("workshop/products/", view=list_products, name="list_products"),
    path("workshop/products/create/", view=create_product, name="create_product"),
    path("workshop/products/<int:pk>/edit/", view=product_detail_view, name="product_detail"),

    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/forms.py
from django import forms
from django.core.exceptions import ValidationError

class ContactForm(forms.Form):
    name = forms.CharField(max_length=255, min_length=8)
    company = forms.CharField(max_length=500, min_length=5)
    email = forms.EmailField()
    phone = forms.CharField(max_length=15, min_length=11)
    message = forms.CharField(widget=forms.Textarea())

    def clean_message(self):
        message = self.cleaned_data['message']
        if len(message) <= 10:
            raise ValidationError('Message is too short and has little to no information. Please write your concerns even clearer')

        if "<script>" in message or "php" in message:
            raise ValidationError("Malicious script detected. Aborting now!")
        return message

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not phone.startswith('+'):
            raise ValidationError('Please ensure to start with +[country code]. eg. +234')
        return phone

    def clean_email(self):
        email = self.cleaned_data['email']
        if not '@' in email:
            raise ValidationError('a valid email must have @ sign within it')
        return email

    def clean_company(self):
        company = self.cleaned_data['company']
        if len(company) <= 5:
            raise ValidationError('Your company name is too short. Are you perhaps using acronyms?')

        if 'trustcrow' or 'trustscrow' in company:
            raise ValidationError('Are you trying to impersonate us?')
        return company

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) <= 6:
            raise ValidationError('Your name is too short. Are you perhaps using acronyms?')
        return name

trustcrow/escrow/forms.py
from datetime import datetime

from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from allauth.account.forms import SignupForm, LoginForm
from countries_plus.models import Country
from trustcrow.users.models import Profile

from .models import (
    Contract,
    Transactions,
    Milestones,
    Dispute,
    DisputeMessages,
)

from trustcrow.utils.logger import LOGGER

User = get_user_model()


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = [
            "contract_title",
            'creator',
            'contract_amount',
            "contract_type",
            "vendor",
            "vendor_phone",
            "vendor_email",
            "vendor_address",
            "buyer",
            "buyer_phone",
            "buyer_email",
            "buyer_address",
            "terms_agreement",
            "terms_for_termination",
        ]


    def clean_vendor(self):
        data = self.cleaned_data['vendor']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_contract_title(self):
        data = self.cleaned_data['contract_title']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_vendor_phone(self):
    #     data = self.cleaned_data['vendor_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(company_phone_I=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a vendor!"))
    #     return data


    def clean_vendor_email(self):
        data = self.cleaned_data['vendor_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        # if User.objects.filter(email=data).exists() and "@" in data:
        #     user = User.objects.get(email=data)
        #     default = "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541"
        #     raise ValidationError(mark_safe(
        #         f"This email belongs to an existing Business / Marchant! <button class='btn-black btn-rounded hover:font-bold duration-300' type='button' data-tooltip-target='tooltip-animation'  data-tooltip-trigger='click'>{user.profile.company_name.title() if user.profile.company_name else user.username}</button> <div id='tooltip-animation' role='tooltip' class='inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-black rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700 space-y-2'><div class='flex items-center'><img class='block h-10 w-10 rounded-full object-fit overflow-hidden hover:object-cover duration-300 flex-none' alt='{user.profile.company_name.title() if user.profile.company_name else user.username}' src='{user.image.thumbnail.url if user.image else default}'><div class='block space-y-2'><a href='{user.get_absolute_url()}' target='_blank' class='block font-semibold hover:font-bold duration-300 text-base'>{user.profile.company_name.title() if user.profile.company_name else user.username}</a><p class='text-s font-medium'>{user.email}</p></div></div><div class='tooltip-arrow' data-popper-arrow></div></div>"))
        return data


    def clean_vendor_address(self):
        data = self.cleaned_data['vendor_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_buyer(self):
        data = self.cleaned_data['buyer']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_buyer_phone(self):
    #     data = self.cleaned_data['buyer_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(phone=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a buyer!"))
    #     return data


    def clean_buyer_email(self):
        data = self.cleaned_data['buyer_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


    def clean_buyer_address(self):
        data = self.cleaned_data['buyer_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestones
        fields = [
            "detail",
            "deadline",
            "price",
        ]

MilestonesFormset = forms.inlineformset_factory(
    Contract,
    Milestones,
    form=MilestoneForm,
    extra=1,
    can_delete=False,
    # can_delete_extra=True,
    min_num=0,
    validate_min=True
)





class DisputeForm(forms.ModelForm):
    class Meta:
        model = Dispute
        fields = [
            "dispute_detail",
            "dispute_resolve",
        ]

class DisputeMessageForm(forms.ModelForm):
    class Meta:
        model = DisputeMessages
        fields = [
            "message"
        ]

trustcrow/workshop/forms.py
from django import forms

from .models import Products, ProductImage

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['title', 'detail', 'price', 'p_type']

trustcrow/currency/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import BankSerializer

from trustcrow.currency.models import Banks


class BankViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = BankSerializer
    queryset = Banks.objects.all()
    lookup_field = "id"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.kwargs['id'], int)
        return self.queryset.filter(id=self.kwargs['id'])

trustcrow/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

trustcrow/templates/pages/about.html
{% extends "base.html" %}

trustcrow/templates/pages/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ block.super }} Contact Us
{% endblock title %}

{% block content %}
<section class="w-screen py-24 justify-center items-center flex flex-col px-4 md:px-24">
  <strong class="block text-center text-sm">Contact Us</strong>
  <h1 class="font-bold text-xl md:text-4xl text-center">We would love to hear from you.</h1>
  <div class="py-24 grid grid-cols-1 md:grid-cols-3 gap-5">
    <div class="text-center space-y-3">
      <strong class="text-bold text-base">Support</strong>
      <p class="block text-center text-sm">Our friendly team is here to help</p>
      <p class="text-center text-primary block">support@trustscrow.com</p>
    </div>
    <div class="text-center space-y-3">
      <strong class="text-bold text-base">Disputes</strong>
      <p class="block text-center text-sm">Disputes and conflicts, get them resolved</p>
      <p class="text-center text-primary block">disputes@trustscrow.com</p>
    </div>
    <div class="text-center space-y-3">
      <strong class="text-bold text-base">Phone</strong>
      <p class="block text-center text-sm">Mon - Fri from 8am - 6pm</p>
      <p class="text-center text-primary block">+(234) 706 485 7582</p>
    </div>
  </div>


</section>

<section id="contact" class="w-full px-4 md:px-24 xl:px-44 md:max-w-6xl md:mx-auto">
  <form action="{% url 'support' %}" data-redirect="{% url 'contact' %}" data-csrf="{{csrf_token}}" class="space-y-5 bg-white p-6 rounded-xl shadow-md" x-data="ContactForm" x-ref="contactForm" method="POST">
    {% csrf_token %}
    <p class="text-center">We expect to hear from you soonest. As such we have created this form to espedite your enquiries thus making it easy to communicate your feelings and ideas directly to us.</p>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-5">
      <div class="relative">
        <input required type="text" name="name" id="id_name"
          class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-warning/60 focus:outline-none focus:ring-0 focus:border-warning peer"
          placeholder=" " />
        <span id="error-wrapper-name" class="hidden bg-red-200 text-red-600 w-full p-2 text-xs mb-4"></span>

        <label for="id_name"
          class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Name / Company Name</label>
      </div>
      <div class="relative">
        <input required type="text" name="phone" id="id_phone"
          class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-warning/60 focus:outline-none focus:ring-0 focus:border-warning peer"
          placeholder=" " />
        <span id="error-wrapper-phone" class="hidden bg-red-200 text-red-600 w-full p-2 text-xs mb-4"></span>

        <label for="id_phone"
          class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Phone</label>
      </div>
      <div class="relative">
        <input required type="email" name="email" id="id_email"
          class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-warning/60 focus:outline-none focus:ring-0 focus:border-warning peer"
          placeholder=" " />
        <span id="error-wrapper-email" class="hidden bg-red-200 text-red-600 w-full p-2 text-xs mb-4"></span>

        <label for="id_email"
          class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Email Address</label>
      </div>
    </div>
    <div class="relative">
      <textarea id="id_message" name="message" rows="4"
        class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        placeholder=""></textarea>
      <span id="error-wrapper-message"
        class="hidden bg-red-200 text-red-600 w-full p-2 text-xs mb-4"></span>

      <label for="id_message"
        class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-warning peer-focus:dark:text-warning/60 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Message</label>
    </div>
    <button type="button" @click="submitForm" class="btn-warning btn-rounded">Submit</button>
  </form>
</section>

{% endblock content %}

trustcrow/templates/pages/offline.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="author" content="Jeremiah David (Darkcodr Codes)">

  <title>You are offline — Trustscrow</title>

  <!-- Inline the page's stylesheet. -->
  <style>
    body {
      font-family: helvetica, arial, sans-serif;
      padding: 2em;
    }

    h1 {
      font-style: italic;
      color: #373fff;
    }

    p {
      margin-block: 1rem;
    }

    button {
      display: block;
    }
  </style>

</head>

<body>
  <h1>You are offline</h1>

  <p>
    The page will automatically reload once the connection is re-established.
    Click the button below to try reloading manually.
  </p>
  <button type="button">⤾ Reload</button>

  <!-- Inline the page's JavaScript file. -->
  <script>
    document.querySelector('button').addEventListener('click', () => {
      window.location.reload();
    });

    // Listen to changes in the network state, reload when online.
    // This handles the case when the device is completely offline.
    window.addEventListener('online', () => {
      window.location.reload();
    });

    // Check if the server is responding & reload the page if it is.
    // This handles the case when the device is online, but the server
    // is offline or misbehaving.
    async function checkNetworkAndReload() {
      try {
        const response = await fetch('.');
        // Verify we get a valid response from the server
        if (response.status >= 200 && response.status < 500) {
          window.location.reload();
          return;
        }
      } catch {
        // Unable to connect to the server, ignore.
      }
      window.setTimeout(checkNetworkAndReload, 2500);
    }

    checkNetworkAndReload();

  </script>
</body>

</html>