config/urls.py
import notifications.urls

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from webpush.views import save_info

from .views import (
    offline_view,
    send_notification,
    service_worker,
    service_worker_map,
    mark_all_read,
    mark_as_read,
    support,
)
from config.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path(
        "contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"
    ),
    path(
        "products/vendify/", TemplateView.as_view(template_name="pages/vendify.html"), name="vendify"
    ),
    path(
        "products/trustpay/", TemplateView.as_view(template_name="pages/trustpay.html"), name="trustpay"
    ),
    path("support/", support, name="support"),
    path("offline/", offline_view, name="offline"),
    path("all-read/", mark_all_read, name="all_read"),
    path("read/<id>/", mark_as_read, name="read"),

    # PWA Urls
    path("sw.js", service_worker, name="service_worker"),
    path("sw.js.map", service_worker_map, name="service_worker_map"),

    # Django Admin, use {% url 'admin:index' %}
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path(
        "jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")
    ),  # Django JET dashboard URLS
    # path("admin/", include("admin_honeypot.urls", "admin_honeypot")),
    path(settings.ADMIN_URL, admin.site.urls),
    path(settings.ADMIN_DOC_URL, include("django.contrib.admindocs.urls")),

    # User management
    path("users/", include("trustcrow.users.urls", namespace="users")),
    path("users/create/new-contract/", TemplateView.as_view(template_name="users/new_contract.html"), name="new_contract"),
    path("escrow/", include("trustcrow.escrow.urls", namespace="escrow")),
    path("accounts/", include("allauth.urls")),

    # Your stuff: custom urls includes go here
    # push notification links
    path("send-notification/", send_notification, name="send_notification"),
    path("webpush/save_information/", view=save_info, name="save_webpush_info"),
    path("webpush/", include("webpush.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# MISC URLS
urlpatterns += [
    path("tinymce/", include("tinymce.urls")),
    path("inbox/notifications/", include(notifications.urls, namespace='notifications')),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml/", sitemap, kwargs={"sitemaps": sitemaps}, name="sitemap"),
    path(
        "robots.txt/",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        name="robots",
    ),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

trustcrow/escrow/urls.py
from django.urls import path

from trustcrow.escrow.views import (
    create_contract,
    vendor_approve,

    create_milestones,
    add_milestones_form,
    milestone_approve,
    detail_milestone,

    approve_product,
    detail_product,
    create_product,
    add_product_form,

    contract_detail,
    contract_detail2,
    list_contracts,
    search_contracts,
    verify_transaction,
    transaction_data,
    list_transactions,
    retry_payment,
    payment_sent,
    # complete_payment,


    # create_contract_service,
    # create_contract_service_milestone,
    # complete_milestone,

    list_customers,
)

app_name = "escrow"
urlpatterns = [
    # contract links
    path("contract/create/", view=create_contract, name="create_contract"),
    path("contract/vendor/approve/<slug>/", view=vendor_approve, name="vendor_approve"),
    path("contract/milestone/approve/<pk>/", view=milestone_approve, name="milestone_approve"),
    path("contract/milestones/<slug>/create/", view=create_milestones, name="create_milestones"),
    path("contract/milestones/<slug>/add-form/", view=add_milestones_form, name="add_milestones_form"),
    path("contract/milestones/<pk>/", view=detail_milestone, name="detail_milestone"),
    path("contract/product/approve/<pk>/", view=approve_product, name="approve_product"),
    path("contract/product/<slug>/create/", view=create_product, name="create_product"),
    path("contract/product/<slug>/add-form/", view=add_product_form, name="add_product_form"),
    path("contract/product/<pk>/", view=detail_product, name="detail_product"),
    path("contract/list/", view=list_contracts, name="list_contracts"),
    path("contract/list/search/", view=search_contracts, name="search_contracts"),
    path("contract/detail/<slug>/", view=contract_detail, name="contract_detail"),
    path("contract/detail/<slug>/<username>/", view=contract_detail2, name="contract_detail2"),
    path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/", view=payment_sent, name="payment_sent"),
    # path("contract/detail/<slug>/<username>/payment_sent/<tf_code>/completed/", view=complete_payment, name="complete_payment"),

    # customers
    path("customers/list/", view=list_customers, name="list_customers"),

    # transactions
    path("transaction/data/", view=transaction_data, name="transaction_data"),
    path("transaction/list/", view=list_transactions, name="list_transactions"),
    path("transaction/verify/<str:ref>/<str:status>/", view=verify_transaction, name="verify_transaction"),
    path("transaction/retry/<str:ref_link>/", view=retry_payment, name="retry_payment"),

    # path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/users/urls.py
from django.urls import path

from trustcrow.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,

    all_users,
    list_products,
    product_detail_view,
    search_products,
    create_product,
    
    add_bank
)

app_name = "users"
urlpatterns = [
    path("", view=all_users, name="all"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),

    path("banks/add/", view=add_bank, name="add_bank"),

    path("workshop/products/search/", view=search_products, name="search_products"),
    path("workshop/products/", view=list_products, name="list_products"),
    path("workshop/products/create/", view=create_product, name="create_product"),
    path("workshop/products/<int:pk>/edit/", view=product_detail_view, name="product_detail"),

    path("<str:username>/", view=user_detail_view, name="detail"),
]

trustcrow/escrow/forms.py
from datetime import datetime

from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from allauth.account.forms import SignupForm, LoginForm
from countries_plus.models import Country
from trustcrow.users.models import Profile

from .models import (
    Contract,
    Transactions,
    Milestones,
    Dispute,
    DisputeMessages,
)

from trustcrow.utils.logger import LOGGER

User = get_user_model()


class ContractForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = [
            "contract_title",
            'creator',
            'contract_amount',
            "contract_type",
            "vendor",
            "vendor_phone",
            "vendor_email",
            "vendor_address",
            "buyer",
            "buyer_phone",
            "buyer_email",
            "buyer_address",
            "terms_agreement",
            "terms_for_termination",
        ]


    def clean_vendor(self):
        data = self.cleaned_data['vendor']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_contract_title(self):
        data = self.cleaned_data['contract_title']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_vendor_phone(self):
    #     data = self.cleaned_data['vendor_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(company_phone_I=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a vendor!"))
    #     return data


    def clean_vendor_email(self):
        data = self.cleaned_data['vendor_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        # if User.objects.filter(email=data).exists() and "@" in data:
        #     user = User.objects.get(email=data)
        #     default = "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541"
        #     raise ValidationError(mark_safe(
        #         f"This email belongs to an existing Business / Marchant! <button class='btn-black btn-rounded hover:font-bold duration-300' type='button' data-tooltip-target='tooltip-animation'  data-tooltip-trigger='click'>{user.profile.company_name.title() if user.profile.company_name else user.username}</button> <div id='tooltip-animation' role='tooltip' class='inline-block absolute invisible z-10 py-2 px-3 text-sm font-medium text-white bg-black rounded-lg shadow-sm opacity-0 transition-opacity duration-300 tooltip dark:bg-gray-700 space-y-2'><div class='flex items-center'><img class='block h-10 w-10 rounded-full object-fit overflow-hidden hover:object-cover duration-300 flex-none' alt='{user.profile.company_name.title() if user.profile.company_name else user.username}' src='{user.image.thumbnail.url if user.image else default}'><div class='block space-y-2'><a href='{user.get_absolute_url()}' target='_blank' class='block font-semibold hover:font-bold duration-300 text-base'>{user.profile.company_name.title() if user.profile.company_name else user.username}</a><p class='text-s font-medium'>{user.email}</p></div></div><div class='tooltip-arrow' data-popper-arrow></div></div>"))
        return data


    def clean_vendor_address(self):
        data = self.cleaned_data['vendor_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    def clean_buyer(self):
        data = self.cleaned_data['buyer']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data

    # def clean_buyer_phone(self):
    #     data = self.cleaned_data['buyer_phone']
    #     if data == "":
    #         raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
    #     if Profile.objects.filter(phone=data).exists():
    #         raise ValidationError(mark_safe("This phone number is already in use buy a buyer!"))
    #     return data


    def clean_buyer_email(self):
        data = self.cleaned_data['buyer_email']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


    def clean_buyer_address(self):
        data = self.cleaned_data['buyer_address']
        if data == "":
            raise ValidationError(mark_safe("This is a required field. Please make a selection!"))
        return data


class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestones
        fields = [
            "detail",
            "deadline",
            "price",
        ]

MilestonesFormset = forms.inlineformset_factory(
    Contract,
    Milestones,
    form=MilestoneForm,
    extra=1,
    can_delete=False,
    # can_delete_extra=True,
    min_num=0,
    validate_min=True
)





class DisputeForm(forms.ModelForm):
    class Meta:
        model = Dispute
        fields = [
            "dispute_detail",
            "dispute_resolve",
        ]

class DisputeMessageForm(forms.ModelForm):
    class Meta:
        model = DisputeMessages
        fields = [
            "message"
        ]

trustcrow/orders/forms.py
from django import forms

from .models import Order, OrderItems

# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['vendor', 'buyer', 'contract']


# class OrderItemForm(forms.ModelForm):
#     class Meta:
#         model = OrderItems
#         fieds = [
#             "id",
#             "order",
#             "product",
#             "quantity",
#             "price",
#         ]

trustcrow/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

trustcrow/workshop/forms.py
from django import forms

from .models import Products, ProductImage

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['title', 'detail', 'price', 'p_type']

trustcrow/currency/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import BankSerializer

from trustcrow.currency.models import Banks


class BankViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = BankSerializer
    queryset = Banks.objects.all()
    lookup_field = "id"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.kwargs['id'], int)
        return self.queryset.filter(id=self.kwargs['id'])

trustcrow/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

trustcrow/templates/snippets/navbar.html
{% load static %}
{% load notifications_tags humanize %}

<header x-transition.duration.500ms id="navbar" :class="{'z-40 fixed duration-300 top-0 left-0 shadow-xl bg-white/70' : showNav, 'z-20 relative bg-white/40' : !showNav}" class="z-50 w-full backdrop-blur-md flex-none py-4 px-4 md:px-24 xl:px-44 flex items-center justify-between">
  <div class="flex space-x-14 items-center">
    <a href="{% url 'home' %}" class="flex items-center space-x-1">
      <img src="{% static 'vendors/images/logo.png' %}" alt="Trustscrow Logo" class="h-10 object-fit">
      <strong class="hidden md:flex text-2xl font-normal uppercase"><span
          class="text-warning font-bold">trust</span>scrow</strong>
    </a>
    <nav class="hidden md:flex items-center space-x-8 text-debug text-sm">
      <a href="{% url 'home' %}#how"
        class="space-y-3 font-semibold hover:text-black hover:text-bold duration-300 group flex flex-col items-center">
        <span class="block">How it works</span>
        <div class="h-[1.75px] group-hover:w-full w-0 duration-300 bg-debug"></div>
      </a>

      <!-- <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="space-y-3 font-semibold hover:text-black hover:text-bold duration-300 group flex flex-col items-center">
        <div class="space-x-4 flex items-center">
          <span class="block">Products</span>
          <svg class="ml-2 w-4 h-4" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
        </div>
        <div class="h-[1.75px] group-hover:w-full w-0 duration-300 bg-debug"></div>
      </button>
      <div id="dropdown" class="hidden z-50 min-w-44 bg-white rounded divide-y divide-debug/40 shadow-xl">
        <div class="max-w-xl mx-auto text-sm">
          <ul aria-labelledby="dropdownDefault" class="space-x-4 grid grid-cols-1 md:grid-cols-2 gap-6 flex items-center p-4">
            <a href="" class="flex p-2 duration-300 hover:scale-105 items-center space-x-4">
              <img src="{% static 'vendors/images/icons/trustpay.png' %}" alt="trustpay icon" class="h-12 block">
              <div class="flex flex-col space-y-1">
                <strong class="text-lg block text-black">Trustpay</strong>
                <p class="text-sm text-debug">Quickly generate links to receive financial support from your customers</p>
              </div>
            </a>
            <a href="" class="flex p-2 duration-300 hover:scale-105 items-center space-x-4">
              <img src="{% static 'vendors/images/icons/vendfy.png' %}" alt="vendify icon" class="h-12 block">
              <div class="flex flex-col space-y-1">
                <strong class="text-lg block text-black">Vendify</strong>
                <p class="text-sm text-debug">As a vendor get verfied so as to build credibility with your customers</p>
              </div>
            </a>
          </ul>
        </div>
      </div> -->


      <a href="{% url 'contact' %}" class="space-y-3 font-semibold hover:text-black hover:text-bold duration-300 group flex flex-col items-center">
        <span class="block">Support</span>
        <div class="h-[1.75px] group-hover:w-full w-0 duration-300 bg-debug"></div>
      </a>
      <!-- <a href="" class="space-y-3 font-semibold hover:text-black hover:text-bold duration-300 group flex flex-col items-center">
        <span class="block">Blog</span>
        <div class="h-[1.75px] group-hover:w-full w-0 duration-300 bg-debug"></div>
      </a> -->
    </nav>
  </div>

  <div class="flex items-center space-x-3 md:space-x-6 font-semibold text-sm">
    {% if request.user.is_authenticated %}
    <button id="dropdownNotificationButton" data-dropdown-toggle="dropdownNotification"
      class=" btn-rounded inline-flex items-center text-sm font-medium text-center text-gray-500 hover:text-gray-900 focus:outline-none dark:hover:text-white dark:text-gray-400"
      type="button">
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg">
        <path
          d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z">
        </path>
      </svg>
      <div class="flex relative">
        {% live_notify_badge  as notify_count %}
        <div class="inline-flex relative -top-2 right-3 max-w-3 max-h-3 flex items-center justify-center bg-red-500 rounded-full border-2 border-white dark:border-gray-900 p-2 text-white">
          <span class="block">{% if notify_count %}{{notify_count}}{% else %}0{% endif %}</span>
        </div>
      </div>
    </button>
    <!-- Dropdown menu -->
    <div id="dropdownNotification"
      class=" btn-rounded hidden z-20 w-full max-w-sm bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-800 dark:divide-gray-700"
      aria-labelledby="dropdownNotificationButton">
      <div class="flex items-center justify-between block py-2 px-4 font-medium text-center text-gray-700 bg-gray-50 dark:bg-gray-800 dark:text-white">
        <strong class="font-bold block">Notifications</strong>
        <button type="button" @click="markAllRead" class="cursor-pointer block text-success text-sm">Mark All Read</button>
      </div>
      <div id="notifications-table" class="divide-y divide-gray-100 dark:divide-gray-700">
        {% for notify in user.notifications.unread %}
        <button type="button" @click="markRead({{notify.id}})" class="flex py-3 px-4 hover:bg-gray-100 dark:hover:bg-gray-700">
          <div class="flex-shrink-0">
            <!-- <img class="w-11 h-11 rounded-full" src="/docs/images/people/profile-picture-1.jpg" alt="Jese image"> -->
            <div
              class="flex absolute justify-center items-center ml-6 -mt-5 w-5 h-5 bg-blue-600 rounded-full border border-white dark:border-gray-800">
              <svg class="w-3 h-3 text-white" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M8.707 7.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l2-2a1 1 0 00-1.414-1.414L11 7.586V3a1 1 0 10-2 0v4.586l-.293-.293z">
                </path>
                <path
                  d="M3 5a2 2 0 012-2h1a1 1 0 010 2H5v7h2l1 2h4l1-2h2V5h-1a1 1 0 110-2h1a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V5z">
                </path>
              </svg>
            </div>
          </div>
          <div class="pl-3 w-full">
            <div class="text-gray-500 text-sm mb-1.5 dark:text-gray-400">New message from <span
                class="font-semibold text-xs">{{notify.actor}}</span>: "{{notify.description}}"</div>
            <div class="text-xs text-blue-600 dark:text-blue-500">{{notify.timestamp|naturaltime}}</div>
          </div>
        </button>
        {% empty %}
        <div class="bg-body text-debug text-sm py-3 px-6 rounded-md">No Notification Available</div>
        {% endfor %}
      </div>

      <!-- view all notification button -->
      <button type="button" @click="drawer = !drawer" @click.outside="drawer = false" class=" btn-rounded w-full text-center flex items-center space-x-2 justify-center block py-2 text-sm font-medium text-center text-gray-900 bg-gray-50 hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-white px-auto">
        <svg class="mr-2 w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor"
          viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
          <path fill-rule="evenodd"
            d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"
            clip-rule="evenodd"></path>
        </svg>
        <span class="block">View all</span>
      </button>


    </div>
    <a href="{% url 'users:detail' user.username %}" class="hidden btn-rounded btn-warning flex-none md:flex items-center md:space-x-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 7.125C2.25 6.504 2.754 6 3.375 6h6c.621 0 1.125.504 1.125 1.125v3.75c0 .621-.504 1.125-1.125 1.125h-6a1.125 1.125 0 01-1.125-1.125v-3.75zM14.25 8.625c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125v8.25c0 .621-.504 1.125-1.125 1.125h-5.25a1.125 1.125 0 01-1.125-1.125v-8.25zM3.75 16.125c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125v2.25c0 .621-.504 1.125-1.125 1.125h-5.25a1.125 1.125 0 01-1.125-1.125v-2.25z" />
      </svg>
      <span class="md:block hidden">Dashboard</span>
    </a>
    <a href="{% url 'account_logout' %}" class="hidden btn-rounded btn-black flex-none md:flex md:items-center md:space-x-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
      </svg>
      <span class="md:block hidden">Logout</span>
    </a>
    {% else %}
    <a href="{% url 'account_login' %}" class="hidden btn-rounded btn-normal md:flex-none flex items-center md:space-x-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
      </svg>
      <span class="md:block hidden">Login</span>
    </a>
    <a href="{% url 'account_signup' %}" class="btn-rounded btn-warning flex-none flex items-center md:space-x-2">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
        <path d="M6.25 6.375a4.125 4.125 0 118.25 0 4.125 4.125 0 01-8.25 0zM3.25 19.125a7.125 7.125 0 0114.25 0v.003l-.001.119a.75.75 0 01-.363.63 13.067 13.067 0 01-6.761 1.873c-2.472 0-4.786-.684-6.76-1.873a.75.75 0 01-.364-.63l-.001-.122zM19.75 7.5a.75.75 0 00-1.5 0v2.25H16a.75.75 0 000 1.5h2.25v2.25a.75.75 0 001.5 0v-2.25H22a.75.75 0 000-1.5h-2.25V7.5z" />
      </svg>
      <span class="md:block hidden">Get Started</span>
    </a>
    {% endif %}
  </div>
</header>